import { Medicine, Pharmacy } from "@/types";

export const pharmacies: Pharmacy[] = [
  {
    id: "mehr-shifo",
    name: {
      uz: "Mehr Shifo Dorixonasi",
      ru: "Аптека Mehr Shifo",
      en: "Mehr Shifo Pharmacy",
      zh: "Mehr Shifo 药房",
      tr: "Mehr Shifo Eczanesi",
    },
    address: {
      uz: "Toshkent shahri, Amir Temur ko'chasi 108",
      ru: "г. Ташкент, улица Амира Темура, 108",
      en: "108 Amir Temur Street, Tashkent",
      zh: "塔什干 Amir Temur 街 108 号",
      tr: "Taşkent, Amir Temur Caddesi 108",
    },
    district: {
      uz: "Yunusobod",
      ru: "Юнусабад",
      en: "Yunusabad",
      zh: "Yunusabad 区",
      tr: "Yunusabad",
    },
    description: {
      uz: "24/7 ishlovchi markaziy dorixona. Retsept bo'yicha dorilar mavjud.",
      ru: "Центральная аптека 24/7. Есть рецептурные препараты.",
      en: "Central 24/7 pharmacy with both OTC and prescription medicines.",
      zh: "市中心 24/7 药房，提供处方与非处方药。",
      tr: "Merkezi 7/24 eczane. Reçeteli ve reçetesiz ilaçlar mevcut.",
    },
    phone: "+998 90 100 11 22",
    image: "/images/pharmacy-placeholder.svg",
    images: ["/images/pharmacy-placeholder.svg"],
    rating: 4.8,
    hasDelivery: true,
    workingHours: {
      is24x7: true,
      open: "00:00",
      close: "23:59",
    },
    createdAt: "2026-01-05T08:00:00.000Z",
    location: { lat: 41.3111, lng: 69.2797 },
  },
  {
    id: "sihat-farm",
    name: {
      uz: "Sihat Farm",
      ru: "Sihat Farm",
      en: "Sihat Farm",
      zh: "Sihat Farm 药房",
      tr: "Sihat Farm",
    },
    address: {
      uz: "Samarqand shahri, Registon ko'chasi 21",
      ru: "г. Самарканд, улица Регистан, 21",
      en: "21 Registan Street, Samarkand",
      zh: "撒马尔罕 Registan 街 21 号",
      tr: "Semerkant, Registan Caddesi 21",
    },
    district: {
      uz: "Registon",
      ru: "Регистан",
      en: "Registan",
      zh: "Registan 区",
      tr: "Registan",
    },
    description: {
      uz: "Oilaviy dorixona, bolalar dorilari va vitaminlar assortimenti keng.",
      ru: "Семейная аптека с широким выбором детских лекарств и витаминов.",
      en: "Family pharmacy with a wide range of pediatric medicines and vitamins.",
      zh: "家庭药房，儿童药品与维生素品类齐全。",
      tr: "Aile eczanesi, çocuk ilaçları ve vitamin çeşitleri geniştir.",
    },
    phone: "+998 91 345 88 90",
    image: "/images/pharmacy-placeholder.svg",
    images: ["/images/pharmacy-placeholder.svg"],
    rating: 4.4,
    hasDelivery: false,
    workingHours: {
      is24x7: false,
      open: "08:00",
      close: "23:00",
    },
    createdAt: "2026-01-19T08:00:00.000Z",
    location: { lat: 39.6542, lng: 66.9597 },
  },
  {
    id: "navo-med",
    name: {
      uz: "Navo Med",
      ru: "Navo Med",
      en: "Navo Med",
      zh: "Navo Med 药房",
      tr: "Navo Med",
    },
    address: {
      uz: "Buxoro shahri, Mustaqillik ko'chasi 44",
      ru: "г. Бухара, улица Мустакиллик, 44",
      en: "44 Mustaqillik Street, Bukhara",
      zh: "布哈拉 Mustaqillik 街 44 号",
      tr: "Buhara, Mustaqillik Caddesi 44",
    },
    district: {
      uz: "Markaz",
      ru: "Центр",
      en: "Central",
      zh: "中心区",
      tr: "Merkez",
    },
    description: {
      uz: "Og'riq qoldiruvchi va antibiotiklar bo'yicha to'liq ta'minot.",
      ru: "Полный ассортимент обезболивающих и антибиотиков.",
      en: "Well-stocked pharmacy for pain relief and antibiotic medicines.",
      zh: "止痛药和抗生素库存充足。",
      tr: "Ağrı kesici ve antibiyotiklerde güçlü stok.",
    },
    phone: "+998 93 667 70 71",
    image: "/images/pharmacy-placeholder.svg",
    images: ["/images/pharmacy-placeholder.svg"],
    rating: 4.5,
    hasDelivery: true,
    workingHours: {
      is24x7: false,
      open: "09:00",
      close: "22:00",
    },
    createdAt: "2026-02-02T08:00:00.000Z",
    location: { lat: 39.7681, lng: 64.4556 },
  },
  {
    id: "care-24",
    name: {
      uz: "Care 24",
      ru: "Care 24",
      en: "Care 24",
      zh: "Care 24 药房",
      tr: "Care 24",
    },
    address: {
      uz: "Farg'ona shahri, Alisher Navoiy ko'chasi 12",
      ru: "г. Фергана, улица Алишера Навои, 12",
      en: "12 Alisher Navoi Street, Fergana",
      zh: "费尔干纳 Alisher Navoi 街 12 号",
      tr: "Fergana, Alişer Nevai Caddesi 12",
    },
    district: {
      uz: "Navoiy",
      ru: "Навои",
      en: "Navoi",
      zh: "Navoi 区",
      tr: "Navoi",
    },
    description: {
      uz: "Tezkor xizmat, onlayn buyurtma qabul qilinadi.",
      ru: "Быстрое обслуживание, принимаются онлайн-заказы.",
      en: "Fast service with support for online medicine orders.",
      zh: "服务快捷，支持线上下单。",
      tr: "Hızlı servis, online sipariş kabul edilir.",
    },
    phone: "+998 94 820 56 78",
    image: "/images/pharmacy-placeholder.svg",
    images: ["/images/pharmacy-placeholder.svg"],
    rating: 4.7,
    hasDelivery: true,
    workingHours: {
      is24x7: true,
      open: "00:00",
      close: "23:59",
    },
    createdAt: "2026-02-18T08:00:00.000Z",
    location: { lat: 40.3894, lng: 71.7878 },
  },
];

export const medicines: Medicine[] = [
  {
    id: "paracetamol-500",
    pharmacyId: "mehr-shifo",
    name: {
      uz: "Paratsetamol 500mg",
      ru: "Парацетамол 500 мг",
      en: "Paracetamol 500mg",
      zh: "对乙酰氨基酚 500mg",
      tr: "Parasetamol 500mg",
    },
    description: {
      uz: "Isitma tushiruvchi va og'riq qoldiruvchi tabletka.",
      ru: "Жаропонижающее и обезболивающее средство.",
      en: "Tablet for fever and mild pain relief.",
      zh: "用于退烧和轻度止痛的片剂。",
      tr: "Ateş düşürücü ve hafif ağrı kesici tablet.",
    },
    category: {
      uz: "Og'riq qoldiruvchi",
      ru: "Обезболивающее",
      en: "Pain Relief",
      zh: "止痛药",
      tr: "Ağrı Kesici",
    },
    price: 12000,
    oldPrice: 15000,
    discountPercent: 20,
    isAvailable: true,
    stockCount: 56,
    manufacturer: {
      uz: "UZ Pharma",
      ru: "UZ Pharma",
      en: "UZ Pharma",
      zh: "UZ 制药",
      tr: "UZ Pharma",
    },
    dosage: {
      uz: "500mg",
      ru: "500 мг",
      en: "500mg",
      zh: "500mg",
      tr: "500mg",
    },
    expiryDate: "2027-03-15",
    prescriptionRequired: false,
    tags: ["fever", "pain", "otc"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-03-01T08:00:00.000Z",
  },
  {
    id: "nurofen",
    pharmacyId: "mehr-shifo",
    name: {
      uz: "Nurofen",
      ru: "Нурофен",
      en: "Nurofen",
      zh: "Nurofen",
      tr: "Nurofen",
    },
    description: {
      uz: "Yallig'lanishga qarshi va og'riqni kamaytiruvchi dori.",
      ru: "Противовоспалительный препарат с обезболивающим эффектом.",
      en: "Anti-inflammatory medicine with pain relief effect.",
      zh: "消炎止痛药。",
      tr: "Antiinflamatuar ağrı kesici ilaç.",
    },
    category: {
      uz: "Yallig'lanishga qarshi",
      ru: "Противовоспалительное",
      en: "Anti-Inflammatory",
      zh: "抗炎药",
      tr: "Antiinflamatuar",
    },
    price: 36000,
    oldPrice: null,
    discountPercent: 0,
    isAvailable: true,
    stockCount: 18,
    manufacturer: {
      uz: "Reckitt",
      ru: "Reckitt",
      en: "Reckitt",
      zh: "Reckitt",
      tr: "Reckitt",
    },
    dosage: {
      uz: "200mg",
      ru: "200 мг",
      en: "200mg",
      zh: "200mg",
      tr: "200mg",
    },
    expiryDate: "2026-12-01",
    prescriptionRequired: false,
    tags: ["pain", "inflammation", "otc"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-03-06T08:00:00.000Z",
  },
  {
    id: "amoxicillin",
    pharmacyId: "navo-med",
    name: {
      uz: "Amoksitsillin 500mg",
      ru: "Амоксициллин 500 мг",
      en: "Amoxicillin 500mg",
      zh: "阿莫西林 500mg",
      tr: "Amoksisilin 500mg",
    },
    description: {
      uz: "Bakterial infeksiyalar uchun antibiotik kapsula.",
      ru: "Антибиотик в капсулах для бактериальных инфекций.",
      en: "Antibiotic capsules for bacterial infections.",
      zh: "用于细菌感染的抗生素胶囊。",
      tr: "Bakteriyel enfeksiyonlar için antibiyotik kapsül.",
    },
    category: {
      uz: "Antibiotik",
      ru: "Антибиотик",
      en: "Antibiotic",
      zh: "抗生素",
      tr: "Antibiyotik",
    },
    price: 48000,
    oldPrice: 55000,
    discountPercent: 13,
    isAvailable: true,
    stockCount: 7,
    manufacturer: {
      uz: "Sandoz",
      ru: "Sandoz",
      en: "Sandoz",
      zh: "Sandoz",
      tr: "Sandoz",
    },
    dosage: {
      uz: "500mg",
      ru: "500 мг",
      en: "500mg",
      zh: "500mg",
      tr: "500mg",
    },
    expiryDate: "2026-06-30",
    prescriptionRequired: true,
    tags: ["antibiotic", "capsule"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-02-20T08:00:00.000Z",
  },
  {
    id: "vitamin-c",
    pharmacyId: "sihat-farm",
    name: {
      uz: "Vitamin C",
      ru: "Витамин C",
      en: "Vitamin C",
      zh: "维生素 C",
      tr: "Vitamin C",
    },
    description: {
      uz: "Immunitetni qo'llab-quvvatlash uchun qo'shimcha.",
      ru: "Добавка для поддержки иммунитета.",
      en: "Supplement for immune system support.",
      zh: "用于增强免疫力的补充剂。",
      tr: "Bağışıklık desteği için takviye.",
    },
    category: {
      uz: "Vitamin",
      ru: "Витамины",
      en: "Vitamins",
      zh: "维生素",
      tr: "Vitamin",
    },
    price: 19000,
    oldPrice: 22000,
    discountPercent: 14,
    isAvailable: true,
    stockCount: 34,
    manufacturer: {
      uz: "Nature Aid",
      ru: "Nature Aid",
      en: "Nature Aid",
      zh: "Nature Aid",
      tr: "Nature Aid",
    },
    dosage: {
      uz: "1000mg",
      ru: "1000 мг",
      en: "1000mg",
      zh: "1000mg",
      tr: "1000mg",
    },
    expiryDate: "2027-09-30",
    prescriptionRequired: false,
    tags: ["vitamin", "immune", "otc"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-02-28T08:00:00.000Z",
  },
  {
    id: "ibuprofen",
    pharmacyId: "sihat-farm",
    name: {
      uz: "Ibuprofen",
      ru: "Ибупрофен",
      en: "Ibuprofen",
      zh: "布洛芬",
      tr: "Ibuprofen",
    },
    description: {
      uz: "Tana og'riqlari va yallig'lanishda qo'llaniladi.",
      ru: "Применяется при болях и воспалениях.",
      en: "Used for pain, swelling, and inflammation.",
      zh: "用于缓解疼痛和炎症。",
      tr: "Ağrı ve inflamasyonda kullanılır.",
    },
    category: {
      uz: "Og'riq qoldiruvchi",
      ru: "Обезболивающее",
      en: "Pain Relief",
      zh: "止痛药",
      tr: "Ağrı Kesici",
    },
    price: 24000,
    oldPrice: null,
    discountPercent: 0,
    isAvailable: true,
    stockCount: 12,
    manufacturer: {
      uz: "Bayer",
      ru: "Bayer",
      en: "Bayer",
      zh: "Bayer",
      tr: "Bayer",
    },
    dosage: {
      uz: "400mg",
      ru: "400 мг",
      en: "400mg",
      zh: "400mg",
      tr: "400mg",
    },
    expiryDate: "2026-11-18",
    prescriptionRequired: false,
    tags: ["pain", "inflammation"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-03-10T08:00:00.000Z",
  },
  {
    id: "loratadine",
    pharmacyId: "care-24",
    name: {
      uz: "Loratadin",
      ru: "Лоратадин",
      en: "Loratadine",
      zh: "氯雷他定",
      tr: "Loratadin",
    },
    description: {
      uz: "Allergiya alomatlarini kamaytiruvchi antihistamin dori.",
      ru: "Антигистаминный препарат при аллергии.",
      en: "Antihistamine for allergy symptoms.",
      zh: "缓解过敏症状的抗组胺药。",
      tr: "Alerji belirtileri için antihistamin.",
    },
    category: {
      uz: "Allergiya",
      ru: "Аллергия",
      en: "Allergy",
      zh: "抗过敏",
      tr: "Alerji",
    },
    price: 21000,
    oldPrice: 25000,
    discountPercent: 16,
    isAvailable: true,
    stockCount: 24,
    manufacturer: {
      uz: "KRKA",
      ru: "KRKA",
      en: "KRKA",
      zh: "KRKA",
      tr: "KRKA",
    },
    dosage: {
      uz: "10mg",
      ru: "10 мг",
      en: "10mg",
      zh: "10mg",
      tr: "10mg",
    },
    expiryDate: "2027-01-21",
    prescriptionRequired: false,
    tags: ["allergy", "antihistamine", "otc"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-01-26T08:00:00.000Z",
  },
  {
    id: "omeprazole",
    pharmacyId: "care-24",
    name: {
      uz: "Omeprazol",
      ru: "Омепразол",
      en: "Omeprazole",
      zh: "奥美拉唑",
      tr: "Omeprazol",
    },
    description: {
      uz: "Oshqozon kislotaliligini kamaytiruvchi kapsula.",
      ru: "Капсулы для снижения кислотности желудка.",
      en: "Capsules that reduce stomach acid production.",
      zh: "降低胃酸分泌的胶囊。",
      tr: "Mide asidini azaltan kapsül.",
    },
    category: {
      uz: "Oshqozon",
      ru: "ЖКТ",
      en: "Gastro",
      zh: "胃肠",
      tr: "Mide",
    },
    price: 27000,
    oldPrice: 31000,
    discountPercent: 12,
    isAvailable: false,
    stockCount: 0,
    manufacturer: {
      uz: "Dr. Reddy's",
      ru: "Dr. Reddy's",
      en: "Dr. Reddy's",
      zh: "Dr. Reddy's",
      tr: "Dr. Reddy's",
    },
    dosage: {
      uz: "20mg",
      ru: "20 мг",
      en: "20mg",
      zh: "20mg",
      tr: "20mg",
    },
    expiryDate: "2026-05-24",
    prescriptionRequired: false,
    tags: ["stomach", "acid"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-01-30T08:00:00.000Z",
  },
  {
    id: "no-shpa",
    pharmacyId: "navo-med",
    name: {
      uz: "No-Spa",
      ru: "Но-Шпа",
      en: "No-Spa",
      zh: "No-Spa",
      tr: "No-Spa",
    },
    description: {
      uz: "Mushak spazmlarini kamaytiruvchi dori.",
      ru: "Препарат для снятия мышечных спазмов.",
      en: "Medicine for relieving muscle spasms.",
      zh: "缓解肌肉痉挛。",
      tr: "Kas spazmlarını azaltan ilaç.",
    },
    category: {
      uz: "Spazmolitik",
      ru: "Спазмолитик",
      en: "Antispasmodic",
      zh: "解痉药",
      tr: "Antispazmodik",
    },
    price: 33000,
    oldPrice: null,
    discountPercent: 0,
    isAvailable: true,
    stockCount: 9,
    manufacturer: {
      uz: "Sanofi",
      ru: "Sanofi",
      en: "Sanofi",
      zh: "Sanofi",
      tr: "Sanofi",
    },
    dosage: {
      uz: "40mg",
      ru: "40 мг",
      en: "40mg",
      zh: "40mg",
      tr: "40mg",
    },
    expiryDate: "2026-10-11",
    prescriptionRequired: false,
    tags: ["spasm", "pain"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-03-12T08:00:00.000Z",
  },
];
