import { Medicine, Pharmacy } from "@/types";

export const pharmacies: Pharmacy[] = [
  {
    id: "mehr-shifo",
    name: {
      uz: "Mehr Shifo Dorixonasi",
      ru: "РђРїС‚РµРєР° Mehr Shifo",
      en: "Mehr Shifo Pharmacy",
      tr: "Mehr Shifo Eczanesi",
    },
    address: {
      uz: "Toshkent shahri, Amir Temur ko'chasi 108",
      ru: "Рі. РўР°С€РєРµРЅС‚, СѓР»РёС†Р° РђРјРёСЂР° РўРµРјСѓСЂР°, 108",
      en: "108 Amir Temur Street, Tashkent",
      tr: "TaЕџkent, Amir Temur Caddesi 108",
    },
    district: {
      uz: "Yunusobod",
      ru: "Р®РЅСѓСЃР°Р±Р°Рґ",
      en: "Yunusabad",
      tr: "Yunusabad",
    },
    description: {
      uz: "24/7 ishlovchi markaziy dorixona. Retsept bo'yicha dorilar mavjud.",
      ru: "Р¦РµРЅС‚СЂР°Р»СЊРЅР°СЏ Р°РїС‚РµРєР° 24/7. Р•СЃС‚СЊ СЂРµС†РµРїС‚СѓСЂРЅС‹Рµ РїСЂРµРїР°СЂР°С‚С‹.",
      en: "Central 24/7 pharmacy with both OTC and prescription medicines.",
      tr: "Merkezi 7/24 eczane. ReГ§eteli ve reГ§etesiz ilaГ§lar mevcut.",
    },
    phone: "+998 90 100 11 22",
    image: "/images/pharmacy-placeholder.svg",
    images: ["/images/pharmacy-placeholder.svg"],
    rating: 4.8,
    hasDelivery: true,
    workingHours: {
      is24x7: true,
      open: "00:00",
      close: "23:59",
    },
    createdAt: "2026-01-05T08:00:00.000Z",
    location: { lat: 41.3111, lng: 69.2797 },
  },
  {
    id: "sihat-farm",
    name: {
      uz: "Sihat Farm",
      ru: "Sihat Farm",
      en: "Sihat Farm",
      tr: "Sihat Farm",
    },
    address: {
      uz: "Samarqand shahri, Registon ko'chasi 21",
      ru: "Рі. РЎР°РјР°СЂРєР°РЅРґ, СѓР»РёС†Р° Р РµРіРёСЃС‚Р°РЅ, 21",
      en: "21 Registan Street, Samarkand",
      tr: "Semerkant, Registan Caddesi 21",
    },
    district: {
      uz: "Registon",
      ru: "Р РµРіРёСЃС‚Р°РЅ",
      en: "Registan",
      tr: "Registan",
    },
    description: {
      uz: "Oilaviy dorixona, bolalar dorilari va vitaminlar assortimenti keng.",
      ru: "РЎРµРјРµР№РЅР°СЏ Р°РїС‚РµРєР° СЃ С€РёСЂРѕРєРёРј РІС‹Р±РѕСЂРѕРј РґРµС‚СЃРєРёС… Р»РµРєР°СЂСЃС‚РІ Рё РІРёС‚Р°РјРёРЅРѕРІ.",
      en: "Family pharmacy with a wide range of pediatric medicines and vitamins.",
      tr: "Aile eczanesi, Г§ocuk ilaГ§larД± ve vitamin Г§eЕџitleri geniЕџtir.",
    },
    phone: "+998 91 345 88 90",
    image: "/images/pharmacy-placeholder.svg",
    images: ["/images/pharmacy-placeholder.svg"],
    rating: 4.4,
    hasDelivery: false,
    workingHours: {
      is24x7: false,
      open: "08:00",
      close: "23:00",
    },
    createdAt: "2026-01-19T08:00:00.000Z",
    location: { lat: 39.6542, lng: 66.9597 },
  },
  {
    id: "navo-med",
    name: {
      uz: "Navo Med",
      ru: "Navo Med",
      en: "Navo Med",
      tr: "Navo Med",
    },
    address: {
      uz: "Buxoro shahri, Mustaqillik ko'chasi 44",
      ru: "Рі. Р‘СѓС…Р°СЂР°, СѓР»РёС†Р° РњСѓСЃС‚Р°РєРёР»Р»РёРє, 44",
      en: "44 Mustaqillik Street, Bukhara",
      tr: "Buhara, Mustaqillik Caddesi 44",
    },
    district: {
      uz: "Markaz",
      ru: "Р¦РµРЅС‚СЂ",
      en: "Central",
      tr: "Merkez",
    },
    description: {
      uz: "Og'riq qoldiruvchi va antibiotiklar bo'yicha to'liq ta'minot.",
      ru: "РџРѕР»РЅС‹Р№ Р°СЃСЃРѕСЂС‚РёРјРµРЅС‚ РѕР±РµР·Р±РѕР»РёРІР°СЋС‰РёС… Рё Р°РЅС‚РёР±РёРѕС‚РёРєРѕРІ.",
      en: "Well-stocked pharmacy for pain relief and antibiotic medicines.",
      tr: "AДџrД± kesici ve antibiyotiklerde gГјГ§lГј stok.",
    },
    phone: "+998 93 667 70 71",
    image: "/images/pharmacy-placeholder.svg",
    images: ["/images/pharmacy-placeholder.svg"],
    rating: 4.5,
    hasDelivery: true,
    workingHours: {
      is24x7: false,
      open: "09:00",
      close: "22:00",
    },
    createdAt: "2026-02-02T08:00:00.000Z",
    location: { lat: 39.7681, lng: 64.4556 },
  },
  {
    id: "care-24",
    name: {
      uz: "Care 24",
      ru: "Care 24",
      en: "Care 24",
      tr: "Care 24",
    },
    address: {
      uz: "Farg'ona shahri, Alisher Navoiy ko'chasi 12",
      ru: "Рі. Р¤РµСЂРіР°РЅР°, СѓР»РёС†Р° РђР»РёС€РµСЂР° РќР°РІРѕРё, 12",
      en: "12 Alisher Navoi Street, Fergana",
      tr: "Fergana, AliЕџer Nevai Caddesi 12",
    },
    district: {
      uz: "Navoiy",
      ru: "РќР°РІРѕРё",
      en: "Navoi",
      tr: "Navoi",
    },
    description: {
      uz: "Tezkor xizmat, onlayn buyurtma qabul qilinadi.",
      ru: "Р‘С‹СЃС‚СЂРѕРµ РѕР±СЃР»СѓР¶РёРІР°РЅРёРµ, РїСЂРёРЅРёРјР°СЋС‚СЃСЏ РѕРЅР»Р°Р№РЅ-Р·Р°РєР°Р·С‹.",
      en: "Fast service with support for online medicine orders.",
      tr: "HД±zlД± servis, online sipariЕџ kabul edilir.",
    },
    phone: "+998 94 820 56 78",
    image: "/images/pharmacy-placeholder.svg",
    images: ["/images/pharmacy-placeholder.svg"],
    rating: 4.7,
    hasDelivery: true,
    workingHours: {
      is24x7: true,
      open: "00:00",
      close: "23:59",
    },
    createdAt: "2026-02-18T08:00:00.000Z",
    location: { lat: 40.3894, lng: 71.7878 },
  },
];

export const medicines: Medicine[] = [
  {
    id: "paracetamol-500",
    pharmacyId: "mehr-shifo",
    name: {
      uz: "Paratsetamol 500mg",
      ru: "РџР°СЂР°С†РµС‚Р°РјРѕР» 500 РјРі",
      en: "Paracetamol 500mg",
      tr: "Parasetamol 500mg",
    },
    description: {
      uz: "Isitma tushiruvchi va og'riq qoldiruvchi tabletka.",
      ru: "Р–Р°СЂРѕРїРѕРЅРёР¶Р°СЋС‰РµРµ Рё РѕР±РµР·Р±РѕР»РёРІР°СЋС‰РµРµ СЃСЂРµРґСЃС‚РІРѕ.",
      en: "Tablet for fever and mild pain relief.",
      tr: "AteЕџ dГјЕџГјrГјcГј ve hafif aДџrД± kesici tablet.",
    },
    category: {
      uz: "Og'riq qoldiruvchi",
      ru: "РћР±РµР·Р±РѕР»РёРІР°СЋС‰РµРµ",
      en: "Pain Relief",
      tr: "AДџrД± Kesici",
    },
    price: 12000,
    oldPrice: 15000,
    discountPercent: 20,
    isAvailable: true,
    stockCount: 56,
    manufacturer: {
      uz: "UZ Pharma",
      ru: "UZ Pharma",
      en: "UZ Pharma",
      tr: "UZ Pharma",
    },
    dosage: {
      uz: "500mg",
      ru: "500 РјРі",
      en: "500mg",
      tr: "500mg",
    },
    expiryDate: "2027-03-15",
    prescriptionRequired: false,
    tags: ["fever", "pain", "otc"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-03-01T08:00:00.000Z",
  },
  {
    id: "nurofen",
    pharmacyId: "mehr-shifo",
    name: {
      uz: "Nurofen",
      ru: "РќСѓСЂРѕС„РµРЅ",
      en: "Nurofen",
      tr: "Nurofen",
    },
    description: {
      uz: "Yallig'lanishga qarshi va og'riqni kamaytiruvchi dori.",
      ru: "РџСЂРѕС‚РёРІРѕРІРѕСЃРїР°Р»РёС‚РµР»СЊРЅС‹Р№ РїСЂРµРїР°СЂР°С‚ СЃ РѕР±РµР·Р±РѕР»РёРІР°СЋС‰РёРј СЌС„С„РµРєС‚РѕРј.",
      en: "Anti-inflammatory medicine with pain relief effect.",
      tr: "Antiinflamatuar aДџrД± kesici ilaГ§.",
    },
    category: {
      uz: "Yallig'lanishga qarshi",
      ru: "РџСЂРѕС‚РёРІРѕРІРѕСЃРїР°Р»РёС‚РµР»СЊРЅРѕРµ",
      en: "Anti-Inflammatory",
      tr: "Antiinflamatuar",
    },
    price: 36000,
    oldPrice: null,
    discountPercent: 0,
    isAvailable: true,
    stockCount: 18,
    manufacturer: {
      uz: "Reckitt",
      ru: "Reckitt",
      en: "Reckitt",
      tr: "Reckitt",
    },
    dosage: {
      uz: "200mg",
      ru: "200 РјРі",
      en: "200mg",
      tr: "200mg",
    },
    expiryDate: "2026-12-01",
    prescriptionRequired: false,
    tags: ["pain", "inflammation", "otc"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-03-06T08:00:00.000Z",
  },
  {
    id: "amoxicillin",
    pharmacyId: "navo-med",
    name: {
      uz: "Amoksitsillin 500mg",
      ru: "РђРјРѕРєСЃРёС†РёР»Р»РёРЅ 500 РјРі",
      en: "Amoxicillin 500mg",
      tr: "Amoksisilin 500mg",
    },
    description: {
      uz: "Bakterial infeksiyalar uchun antibiotik kapsula.",
      ru: "РђРЅС‚РёР±РёРѕС‚РёРє РІ РєР°РїСЃСѓР»Р°С… РґР»СЏ Р±Р°РєС‚РµСЂРёР°Р»СЊРЅС‹С… РёРЅС„РµРєС†РёР№.",
      en: "Antibiotic capsules for bacterial infections.",
      tr: "Bakteriyel enfeksiyonlar iГ§in antibiyotik kapsГјl.",
    },
    category: {
      uz: "Antibiotik",
      ru: "РђРЅС‚РёР±РёРѕС‚РёРє",
      en: "Antibiotic",
      tr: "Antibiyotik",
    },
    price: 48000,
    oldPrice: 55000,
    discountPercent: 13,
    isAvailable: true,
    stockCount: 7,
    manufacturer: {
      uz: "Sandoz",
      ru: "Sandoz",
      en: "Sandoz",
      tr: "Sandoz",
    },
    dosage: {
      uz: "500mg",
      ru: "500 РјРі",
      en: "500mg",
      tr: "500mg",
    },
    expiryDate: "2026-06-30",
    prescriptionRequired: true,
    tags: ["antibiotic", "capsule"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-02-20T08:00:00.000Z",
  },
  {
    id: "vitamin-c",
    pharmacyId: "sihat-farm",
    name: {
      uz: "Vitamin C",
      ru: "Р’РёС‚Р°РјРёРЅ C",
      en: "Vitamin C",
      tr: "Vitamin C",
    },
    description: {
      uz: "Immunitetni qo'llab-quvvatlash uchun qo'shimcha.",
      ru: "Р”РѕР±Р°РІРєР° РґР»СЏ РїРѕРґРґРµСЂР¶РєРё РёРјРјСѓРЅРёС‚РµС‚Р°.",
      en: "Supplement for immune system support.",
      tr: "BaДџД±ЕџД±klД±k desteДџi iГ§in takviye.",
    },
    category: {
      uz: "Vitamin",
      ru: "Р’РёС‚Р°РјРёРЅС‹",
      en: "Vitamins",
      tr: "Vitamin",
    },
    price: 19000,
    oldPrice: 22000,
    discountPercent: 14,
    isAvailable: true,
    stockCount: 34,
    manufacturer: {
      uz: "Nature Aid",
      ru: "Nature Aid",
      en: "Nature Aid",
      tr: "Nature Aid",
    },
    dosage: {
      uz: "1000mg",
      ru: "1000 РјРі",
      en: "1000mg",
      tr: "1000mg",
    },
    expiryDate: "2027-09-30",
    prescriptionRequired: false,
    tags: ["vitamin", "immune", "otc"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-02-28T08:00:00.000Z",
  },
  {
    id: "ibuprofen",
    pharmacyId: "sihat-farm",
    name: {
      uz: "Ibuprofen",
      ru: "РР±СѓРїСЂРѕС„РµРЅ",
      en: "Ibuprofen",
      tr: "Ibuprofen",
    },
    description: {
      uz: "Tana og'riqlari va yallig'lanishda qo'llaniladi.",
      ru: "РџСЂРёРјРµРЅСЏРµС‚СЃСЏ РїСЂРё Р±РѕР»СЏС… Рё РІРѕСЃРїР°Р»РµРЅРёСЏС….",
      en: "Used for pain, swelling, and inflammation.",
      tr: "AДџrД± ve inflamasyonda kullanД±lД±r.",
    },
    category: {
      uz: "Og'riq qoldiruvchi",
      ru: "РћР±РµР·Р±РѕР»РёРІР°СЋС‰РµРµ",
      en: "Pain Relief",
      tr: "AДџrД± Kesici",
    },
    price: 24000,
    oldPrice: null,
    discountPercent: 0,
    isAvailable: true,
    stockCount: 12,
    manufacturer: {
      uz: "Bayer",
      ru: "Bayer",
      en: "Bayer",
      tr: "Bayer",
    },
    dosage: {
      uz: "400mg",
      ru: "400 РјРі",
      en: "400mg",
      tr: "400mg",
    },
    expiryDate: "2026-11-18",
    prescriptionRequired: false,
    tags: ["pain", "inflammation"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-03-10T08:00:00.000Z",
  },
  {
    id: "loratadine",
    pharmacyId: "care-24",
    name: {
      uz: "Loratadin",
      ru: "Р›РѕСЂР°С‚Р°РґРёРЅ",
      en: "Loratadine",
      tr: "Loratadin",
    },
    description: {
      uz: "Allergiya alomatlarini kamaytiruvchi antihistamin dori.",
      ru: "РђРЅС‚РёРіРёСЃС‚Р°РјРёРЅРЅС‹Р№ РїСЂРµРїР°СЂР°С‚ РїСЂРё Р°Р»Р»РµСЂРіРёРё.",
      en: "Antihistamine for allergy symptoms.",
      tr: "Alerji belirtileri iГ§in antihistamin.",
    },
    category: {
      uz: "Allergiya",
      ru: "РђР»Р»РµСЂРіРёСЏ",
      en: "Allergy",
      tr: "Alerji",
    },
    price: 21000,
    oldPrice: 25000,
    discountPercent: 16,
    isAvailable: true,
    stockCount: 24,
    manufacturer: {
      uz: "KRKA",
      ru: "KRKA",
      en: "KRKA",
      tr: "KRKA",
    },
    dosage: {
      uz: "10mg",
      ru: "10 РјРі",
      en: "10mg",
      tr: "10mg",
    },
    expiryDate: "2027-01-21",
    prescriptionRequired: false,
    tags: ["allergy", "antihistamine", "otc"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-01-26T08:00:00.000Z",
  },
  {
    id: "omeprazole",
    pharmacyId: "care-24",
    name: {
      uz: "Omeprazol",
      ru: "РћРјРµРїСЂР°Р·РѕР»",
      en: "Omeprazole",
      tr: "Omeprazol",
    },
    description: {
      uz: "Oshqozon kislotaliligini kamaytiruvchi kapsula.",
      ru: "РљР°РїСЃСѓР»С‹ РґР»СЏ СЃРЅРёР¶РµРЅРёСЏ РєРёСЃР»РѕС‚РЅРѕСЃС‚Рё Р¶РµР»СѓРґРєР°.",
      en: "Capsules that reduce stomach acid production.",
      tr: "Mide asidini azaltan kapsГјl.",
    },
    category: {
      uz: "Oshqozon",
      ru: "Р–РљРў",
      en: "Gastro",
      tr: "Mide",
    },
    price: 27000,
    oldPrice: 31000,
    discountPercent: 12,
    isAvailable: false,
    stockCount: 0,
    manufacturer: {
      uz: "Dr. Reddy's",
      ru: "Dr. Reddy's",
      en: "Dr. Reddy's",
      tr: "Dr. Reddy's",
    },
    dosage: {
      uz: "20mg",
      ru: "20 РјРі",
      en: "20mg",
      tr: "20mg",
    },
    expiryDate: "2026-05-24",
    prescriptionRequired: false,
    tags: ["stomach", "acid"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-01-30T08:00:00.000Z",
  },
  {
    id: "no-shpa",
    pharmacyId: "navo-med",
    name: {
      uz: "No-Spa",
      ru: "РќРѕ-РЁРїР°",
      en: "No-Spa",
      tr: "No-Spa",
    },
    description: {
      uz: "Mushak spazmlarini kamaytiruvchi dori.",
      ru: "РџСЂРµРїР°СЂР°С‚ РґР»СЏ СЃРЅСЏС‚РёСЏ РјС‹С€РµС‡РЅС‹С… СЃРїР°Р·РјРѕРІ.",
      en: "Medicine for relieving muscle spasms.",
      tr: "Kas spazmlarД±nД± azaltan ilaГ§.",
    },
    category: {
      uz: "Spazmolitik",
      ru: "РЎРїР°Р·РјРѕР»РёС‚РёРє",
      en: "Antispasmodic",
      tr: "Antispazmodik",
    },
    price: 33000,
    oldPrice: null,
    discountPercent: 0,
    isAvailable: true,
    stockCount: 9,
    manufacturer: {
      uz: "Sanofi",
      ru: "Sanofi",
      en: "Sanofi",
      tr: "Sanofi",
    },
    dosage: {
      uz: "40mg",
      ru: "40 РјРі",
      en: "40mg",
      tr: "40mg",
    },
    expiryDate: "2026-10-11",
    prescriptionRequired: false,
    tags: ["spasm", "pain"],
    image: "/images/medicine-placeholder.svg",
    createdAt: "2026-03-12T08:00:00.000Z",
  },
];

